[window]
padding = { x = 10, y = 10 }
opacity = 0.95
blur = false

[font]
size = 12.0
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }

[colors.primary]
background = "#1e2a33"  # Background color - Dark Blue Gray
foreground = "#cddfe4"  # Foreground color - Light Gray Blue

[colors.cursor]
text = "CellBackground" # Cursor text color matches cell background for contrast
cursor = "#88c0b0"      # Cursor color - Soft Cyan Green

[colors.normal]
black   = "#1e2a33"  # Black - Dark Blue Gray
red     = "#c27d7d"  # Red - Muted Rose
green   = "#9bd6c3"  # Green - Soft Mint Green
yellow  = "#cfcfa0"  # Yellow - Pale Olive
blue    = "#81a1c1"  # Blue - Soft Steel Blue
magenta = "#b48ead"  # Magenta - Dusty Purple
cyan    = "#88c0b0"  # Cyan - Soft Cyan Green
white   = "#cddfe4"  # White - Light Gray Blue

[colors.bright]
black   = "#3b4d57"  # Bright Black - Slate Gray
red     = "#d47777"  # Bright Red - Warm Rose
green   = "#bdeee0"  # Bright Green - Light Mint
yellow  = "#f1f1b5"  # Bright Yellow - Soft Butter
blue    = "#a3c0df"  # Bright Blue - Light Steel Blue
magenta = "#d2a4d6"  # Bright Magenta - Light Lavender
cyan    = "#a1d9cb"  # Bright Cyan - Light Aqua Green
white   = "#dff4f8"  # Bright White - Very Light Blue
