# Add a blank line between prompts
add_newline = true

# Define the prompt format:
# 1st line: username, hostname, and directory
# 2nd line: command prompt character
format = """
[┌─](cyan)\
[$username@$hostname](magenta)\
[$directory](cyan)
[└─](cyan)$character"""

# Username settings
[username]
style_user = "#a0e1ef"        # Ice blue color for normal users
style_root = "bold red"       # Bold red color when root user
format = "[$user]($style)"
show_always = true

# Hostname settings
[hostname]
ssh_only = false              # Show hostname even if not SSH session
style = "magenta"
format = "[$hostname]($style) "
trim_at = "."                 # Trim hostname at first dot
disabled = false

# Directory settings
[directory]
style = "cyan bold"           # Cyan bold style for directory path
read_only = " 󰌾"             # Lock icon for read-only directories

# Command prompt character settings
[character]
success_symbol = "[\\$](bold white) "  # White $ on success
error_symbol = "[\\$](bold red) "      # Red $ on error
